### ISSUE TITLE
Issue: Conflict with Chisel (?)

### ISSUE THREAD

**Issue by Skkubah** [KillerMapper/roadstuff#10]
Hello,

A while ago, I've decided to make a private modpack, and I've decided to add Road Stuff and Chisel, and while playing in survival mode, I have noted that using the Chisel tool to make road lines blocks (both concrete and asphalt), etc, makes the recipe for those lines (using dyes...) pretty much obsolete. Is this intended or a conflict?

![2017-01-19_23 07 23](https://cloud.githubusercontent.com/assets/10351506/22131709/3a4a54b4-de9c-11e6-854c-e4e5e8526502.png)

![2017-01-19_23 08 14](https://cloud.githubusercontent.com/assets/10351506/22131710/3d9509fc-de9c-11e6-90c7-85d76adf6b69.png)

Thank you for your time.

**Comment by KillerMapper** [comment]
Hello, no this is not a bug. The recipes with dyes are only here to allow players to craft the blocks if Chisel is not installed. I myself recommend using Chisel in the mod description, since I want this mod to be easy to use with so much different blocks that would fill the inventory too quickly.
