### ISSUE TITLE
Can't paint with brush

### ISSUE THREAD

**Issue by ThaBest2008** [KillerMapper/roadstuff#21]
**FILL THIS!**
• Minecraft version: 1.14.4
• Forge version: 28.2.3
• Road Stuff version: 2.1.1
• Other mods used or modpack: Create, Backpacked, Obfuscate, WorldEdit, Slopes, MrCrayfish's Furniture Mod, CC: Tweaked, MrCrayfish's Vehicle Mod, Just Enough Items, Prefab, XL Food Mod, Placeable Items, Cooking for Blockheads, SecurityCraft and Storage Drawers.

**Describe the bug**
When I try to paint with the paintbrush, it doesn't work. It pops up the menu with the selection.

**Comment by MapperTV** [comment]
Which input are you using? You need to "attack" (by default left click) to paint lines. If you right click (or whatever binding for "place block") it will open the menu.

**Comment by ThaBest2008** [comment]
Ok. Thank you!
