### ISSUE TITLE
[1.16.4] Bitumen tag in recipes

### ISSUE THREAD

**Issue by Terpo** [KillerMapper/roadstuff#24]
I've got a small suggestion for the latest build of Road Stuff and Mapper Base: 1.16.4-4.2.0

The bitumen of Mapper Base and Immersive Petroleum are both tagged with forge:bitumen.
The recipes for Road Stuff and Mapper Base are using mapperbase:raw_bitumen instead of the forge tag. Could you change the recipes from using the item to the forge:bitumen tag?

With this the integration to other mods would be much easier.

**Comment by MapperTV** [comment]
That's something I forgot to do when i added the tag. Will add it later in the meanwhile it is possible to add the tag through a datapack.
