### ISSUE TITLE
[Suggestion] All colors for lines

### ISSUE THREAD

**Issue by ExDomino** [KillerMapper/roadstuff#31]
Hello, I know lines are only in white or yellow usualy, but with your bucket system, you could support all colors for line marks. It should really nice, thank you in advance.

**Comment by MapperTV** [comment]
While I am not against having all the colors it may have a negative impact in terms of memory consumption and loading time as this would add thousands of new blocks. We're talking about 14k-16k additional blocks which is not nothing. And this will be worse if I add new road types. This is why for now I limited the amount of colors.

**Comment by ExDomino** [comment]
Ok I understand.
