### ISSUE TITLE
Paint lines vanish on roads

### ISSUE THREAD

**Issue by Lynzzyr** [KillerMapper/roadstuff#33]
• Minecraft version: 1.16.5
• Forge version: 36.2.2
• Road Stuff version: 1.16.5-4.3.0
• Other mods used or modpack: OptiFine, Create, Flywheel, HammerLib, Immersive Engineering, Lotta Terracotta, Mapper Base, More Minecarts and Rails, Pane In The Glass, Solar Flux Reborn, Sweet Concrete

This is the first time that I've used this mod, and after figuring out how to paint roads (and getting really excited about it), I noticed that the lines would start to vanish as I got farther away from them. I found a comment relating to a similar if not the same issue on the mod's main Forge page, but it didn't describe how to fix the issue. I did notice that the issue got fixed when I would remove OptiFine.

So maybe this is an OptiFine incompatibility?

**Comment by MapperTV** [comment]
Yes this is a problem from Optifine. I can't do anything about it. The road blocks have an additional face on the top for the painted line (this way I can reuse the same line textures for every color and road surface and save thousands of files) and Optifine probably removes it while trying to optimize the rendering.
