### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by emanuele246gi** [KillerMapper/roadstuff#35]
Hi, I would like to create a datapack for my modpack which complicates crafting recipes a bit, I did it successfully with other mods but with Road Stuff I can't (I haven't tried MB nor EC, at the moment), I checked every character to see if I did some typos or something like that, but it was everything ok.

What can I do?

I'm using the latest and only version of the mod for 1.18.2 and, to create the datapacks, I'm using the Global Packs mod. (Forge version 40.1.73

**Comment by MapperTV** [comment]
What is the problem exactly?

**Comment by emanuele246gi** [comment]
When I launch the /reload command, it doesn't change anything, I obviously did this with the other mods as well, as I said, and it worked fine. I don't understand if I'm doing something wrong, but it's a bit weird due to the fact that I do the exact same thing to these other mods without problems. I don't know if I clarified my issue better than before

**Comment by emanuele246gi** [comment]
Yep, it does like that with Embellishcraft too

**Comment by MapperTV** [comment]
I have no idea then. The mods only have vanilla recipe types. Maybe something changed in 1.18.2, I didn't make the update so cant tell.

**Comment by emanuele246gi** [comment]
Mh, I understand, thank you anyway for your help! I'll see how I can fix it

**Comment by emanuele246gi** [comment]
I talked with Global Packs devs and they said to me that probably there is an high priority datapack in the mod that makes exclude any external intervention, what do you think?

**Comment by MapperTV** [comment]
I have no clue at all. The mods have nothing special.

**Comment by emanuele246gi** [comment]
Thank you for your help anyway, I appreciated it ^^

**Comment by emanuele246gi** [comment]
Hey man, Global Packs has been updated and the datapacks now work just fine! Thank you again tho!
