### ISSUE TITLE
Game crash on launch because unable to load mod

### ISSUE THREAD

**Issue by YassaaaTU** [KillerMapper/roadstuff#37]
• Minecraft version: 1.19.2
• Forge version: 43.2.11
• Road Stuff version: 7.0.1
• Other mods used or modpack: ATM8 modified to have 400+ mods (you can find the mod list in the crash report)

---

**Describe the bug:**

1. Launch game
2. wait for it to load
3. watch it crash because it is unable to load the Road Stuff mod

**Crash Report:**
[Crashy.net](https://crashy.net/755c8d94-b8e1-4c61-984f-62cc8b9366b2)
*OR*
[mclo.gs](https://mclo.gs/7TTqe6d)

**Comment by MapperTV** [comment]
I didn't work on the 1.19.2, I didn't even know an update was published. Since I didn't touch the code for more than a year I can't help anymore.

I think the updated repo is this one, you may have better luck there:
https://github.com/Aero-Tech/roadstuff

**Comment by YassaaaTU** [comment]
Lmao I wonder why the modpage still link to this github. Thanks for the link though
