### ISSUE TITLE
Paintbrush is not working

### ISSUE THREAD

**Issue by BernardoXD72** [KillerMapper/roadstuff#38]
**FILL THIS!**
• Minecraft version:1.19.2 Java
• Forge version:Forge 43.2.0
• Road Stuff version:roadstuff-1.19.2-7.0.1
• Other mods used or modpack:
Architetury API
Attribute Fix
Biomes O' Plenty
Common Roads
Decorative Blocks
Open Blocks Elevator
Just Enough Items
Journey Map
Mapper Base
Mouse Tweaks
Minecraft Transit Railway
Station Decoration Addon
Nemo Transit's Expansion
NX Roads and Skyscrapers
Road Stuff
Saro Road Blocks
Saro Road Signs
Sophisticated Backpacks
Sophisticated Core
Space Station
Spark
Terra Blender
Torch Master
Train Road Signs
World Edit
When i click to paint, it dont paint

**Comment by MapperTV** [comment]
For the 1.19 version I am not able to help as I didn't make it. There is another repo, the link on Curseforge was outdated, I updated it: https://github.com/Aero-Tech/roadstuff/issues

Please report the bug here, you will have more luck.
